all:
	pdflatex compress
	pdflatex compress
	bibtex compress
	bibtex compress
	pdflatex compress
	pdflatex compress
	open compress.pdf

arxiv:
	pdflatex compress_arxiv
	pdflatex compress_arxiv
	bibtex compress_arxiv
	bibtex compress_arxiv
	pdflatex compress_arxiv
	pdflatex compress_arxiv
	open compress_arxiv.pdf

clean:
	rm *.aux *.brf *.pdf *.log *.bbl *.blg *.dvi *.ps *.out

pdfcrop:
	pdfcrop img/conv.pdf
